#!/bin/bash
#get window with id=$1 from the scratchpad
id=$1;
#id=${id##*:};

#notify-send 'Getting window id: '$id' from scratchpad'

i3-msg ' [ id="'$id'" ] scratchpad show'
i3-msg ' [ id="'$id'" ] floating toggle'
