#!/bin/bash
#get window with id=$1 from the scratchpad
rclick=$1
id=$2
#id=${id##*:};

#notify-send 'Getting window id: '$id' from scratchpad'

i3-msg ' [ id="'$id'" ] scratchpad show'

if [ $rclick -eq 0 ] #only float toggle if leftclick
 then i3-msg ' [ id="'$id'" ] floating toggle'
fi
